[[links]]
    iconset = "fab"
    icon = "mastodon"
    title = "Mastodon"
    url = "https://chaos.social/@dreadwarrior"
[[links]]
    iconset = "fab"
    icon = "github"
    title = "GitHub"
    url = "https://github.com/dreadwarrior"
[[links]]
    icon = "id-card-alt"
    title = "Portfolio / Resume"
    url = "https://dreadlabs.de/"

[books]
    coversPath = "images/books/covers/"