[colors]
    # "sea"
#    background = "#1C2541"
#    foreground = "#FFFFFF"
#    hover = "#F3B700"
    # dark background, light foreground
#   background = "#26242F"
#   foreground = "#ffffff"
#   hover = "#8DAFDC"
    # https://coolors.co/738290-a1b5d8-fffcf7-e4f0d0-c2d8b9
    background = "#FFFCF7"
    foreground = "#738290"
    hover = "#A1B5D8"

[[links]]
    icon = "mastodon"
    title = "Mastodon"
    url = "https://chaos.social/@dreadwarrior"
[[links]]
    icon = "github"
    title = "GitHub"
    url = "https://github.com/dreadwarrior"
[[links]]
    iconset = "fas"
    icon = "id-card-alt"
    title = "Portfolio / Resume"
    url = "https://dreadlabs.de/"

[books]
    coversPath = "images/books/covers/"