#############################  Display  #############################

# Verbose program output
# Accepts log level: "error", "warn", "info", "debug", "trace"
verbose = "error"

# Don't show interactive progress bar while checking links.
no_progress = true

mode = "plain"

#############################  Requests  ############################

# Website timeout from connect to response finished.
timeout = 20

# Minimum wait time in seconds between retries of failed requests.
retry_wait_time = 5

#############################  Exclusions  ##########################

# Ignore case of paths when matching glob patterns.
glob_ignore_case = true

# Exclude URLs and mail addresses from checking (supports regex).
exclude = [
    '^https://www\.thalia\.de' # (Temporarily) exclude Thalia URLs, because of activated CloudFlare's "I'm under attack" mode.
]
