version: '3'

includes:

  book:
    taskfile: ./BookTasks.yml

  dev:
    taskfile: ./DevelopmentTasks.yml

  maintenance:
    taskfile: ./MaintenanceTasks.yml

  new.book:
    taskfile: ./NewBookTasks.yml