version: '3'

tasks:
  de.book.wishlist:
    cmds:
      - task: _unread-book
        vars:
          BOOKLIST: 'wishlist'
          LANGUAGE: '{{ (split "." .TASK)._0 }}'

  en.book.wishlist:
    cmds:
      - task: _unread-book
        vars:
          BOOKLIST: 'wishlist'
          LANGUAGE: '{{ (split "." .TASK)._0 }}'

  de.book.unread:
    cmds:
      - task: _unread-book
        vars:
          BOOKLIST: 'unread'
          LANGUAGE: '{{ (split "." .TASK)._0 }}'

  en.book.unread:
    cmds:
      - task: _unread-book
        vars:
          BOOKLIST: 'unread'
          LANGUAGE: '{{ (split "." .TASK)._0 }}'

  de.book.completed:
    cmds:
      - task: _completed-book
        vars:
          LANGUAGE: '{{ (split "." .TASK)._0 }}'

  en.book.completed:
    cmds:
      - task: _completed-book
        vars:
          LANGUAGE: '{{ (split "." .TASK)._0 }}'

  synopsis:
    vars:
      SOURCE:
        sh: "yq --front-matter='extract' '.source' {{.BOOK}} | tr -d '\n'"
    cmds:
      - curl --silent {{.SOURCE}} | htmlq --text '{{.SELECTOR}}' | fold -w 80 -s | xargs -0 printf "\n\n%s" >> {{.BOOK}}

  _unread-book:
    internal: true
    vars:
      FORMATTED_ISBN:
        sh: 'jbang --quiet ./script/isbn13.java {{.ISBN}}'
      TARGET: 'books/{{.FORMATTED_ISBN}}.md'
    cmds:
      - echo "Create {{.BOOKLIST}} book for ISBN {{.FORMATTED_ISBN}}"
      - hugo new content --kind books.{{.LANGUAGE}} {{.TARGET}}
      - task: _update-booklist
        vars:
          BOOKLIST: '{{.BOOKLIST}}'
          TARGET: 'content/{{.TARGET}}'
      - task: _add-to-vcs
        vars:
          REF: 'content/{{.TARGET}}'

  _completed-book:
    internal: true
    vars:
      FORMATTED_ISBN:
        sh: 'jbang --quiet ./script/isbn13.java {{.ISBN}}'
      TARGET: 'books/{{.FORMATTED_ISBN}}'
    cmds:
      - echo "Create completed book for ISBN {{.FORMATTED_ISBN}}"
      - hugo new content --kind books.{{.LANGUAGE}} {{.TARGET}}/index.md
      - task: _update-booklist
        vars:
          BOOKLIST: 'completed'
          TARGET: 'content/{{.TARGET}}/index.md'
      - cp ./archetypes/review.md.dist content/{{.TARGET}}/review.md
      - task: _add-to-vcs
        vars:
          REF: 'content/{{.TARGET}}/'

  _update-booklist:
    internal: true
    cmds:
      - yq --front-matter=process -i '.booklists = ["{{.BOOKLIST}}"]' {{.TARGET}}

  _add-to-vcs:
    internal: true
    cmds:
      - git add {{.REF}}