version: '3'

tasks:
  de.book.wishlist:
    cmds:
      - task: _wishlist-book
        vars:
          LANGUAGE: '{{ (split "." .TASK)._0 }}'

  en.book.wishlist:
    cmds:
      - task: _wishlist-book
        vars:
          LANGUAGE: '{{ (split "." .TASK)._0 }}'

  de.book.completed:
    cmds:
      - task: _completed-book
        vars:
          LANGUAGE: '{{ (split "." .TASK)._0 }}'

  en.book.completed:
    cmds:
      - task: _completed-book
        vars:
          LANGUAGE: '{{ (split "." .TASK)._0 }}'

  synopsis:
    vars:
      SOURCE:
        sh: "yq --front-matter='extract' '.source' {{.BOOK}} | tr -d '\n'"
    cmds:
      - curl --silent {{.SOURCE}} | htmlq --text '{{.SELECTOR}}' | fold -w 80 -s | xargs -0 printf "\n\n%s" >> {{.BOOK}}

  _wishlist-book:
    internal: true
    vars:
      FORMATTED_ISBN:
        sh: 'jbang --quiet ./script/isbn13.java {{.ISBN}}'
      TARGET: 'books/{{.FORMATTED_ISBN}}.md'
    cmds:
      - echo "Create wishlist book for ISBN {{.FORMATTED_ISBN}}"
      - hugo new content --kind books.{{.LANGUAGE}} {{.TARGET}}
      - task: _replace-bookshelf-placeholder
        vars:
          BOOKSHELF: 'wishlist'
          TARGET: 'content/{{.TARGET}}'
      - task: _add-to-vcs
        vars:
          REF: 'content/{{.TARGET}}'

  _completed-book:
    internal: true
    vars:
      FORMATTED_ISBN:
        sh: 'jbang --quiet ./script/isbn13.java {{.ISBN}}'
      TARGET: 'books/{{.FORMATTED_ISBN}}'
    cmds:
      - echo "Create completed book for ISBN {{.FORMATTED_ISBN}}"
      - hugo new content --kind books.{{.LANGUAGE}} {{.TARGET}}/index.md
      - task: _replace-bookshelf-placeholder
        vars:
          BOOKSHELF: 'completed'
          TARGET: 'content/{{.TARGET}}/index.md'
      - cp ./archetypes/review.md.dist content/{{.TARGET}}/review.md
      - task: _add-to-vcs
        vars:
          REF: 'content/{{.TARGET}}/'

  _replace-bookshelf-placeholder:
    internal: true
    cmds:
      - sed -i.bak "s~###BOOKSHELF###~{{.BOOKSHELF}}~g" {{.TARGET}}
      - rm -f {{.TARGET}}.bak

  _add-to-vcs:
    internal: true
    cmds:
      - git add {{.REF}}