name: Check for broken links in content files.

on:
  schedule:
    - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          # Which go-task version to use.
          version: 3.x

      - uses: actions/checkout@v4

      - name: Check book cover URLs
        run: task maintenance:broken-links.books.covers
        continue-on-error: true

      - name: Check book excerpt source URLs
        run: task maintenance:broken-links.books.sources
        continue-on-error: true

      - name: Check book permalink URLs
        run: task maintenance:broken-links.books.permalinks
        continue-on-error: true